import type { CasualMap, CasualMapCategory } from "$types/maps";
import { parse } from "vdf-parser";
import { readFile, writeFile } from "node:fs/promises";
import Settings from "$src/settings/settings";
import { join } from "node:path";

await Settings.init();

const tfPath = Settings.get("tfPath");
const stringsPath = join(tfPath, "resource", "tf_english.txt");
const itemsPath = join(tfPath, "scripts", "items", "items_game.txt");

// The files are in different encodings, for some reason
let stringsBuffer = await readFile(stringsPath, "utf16le");
let itemsBuffer = await readFile(itemsPath, "utf-8");

const strings = parse<any>(stringsBuffer).lang.Tokens;
const items = parse<any>(itemsBuffer).items_game;

// Get information about the maps
const mapInfo: Record<string, CasualMap> = {};
let largestNumber = 0;

const mapsList = Object.values<any>(items.master_maps_list);
for(let i = 0; i < mapsList.length; i++) {
	const map = mapsList[i];

	const name = str(map.localizedname);
	const number = Math.floor(i / 32);
	const bit = BigInt(i % 32);

	if(number > largestNumber) largestNumber = number;
	mapInfo[map.name] = { name, number, bit };
}

// Get map categories
const mapTypes = ["core", "alternative", "special_events"];
const mapGroups = Object.values<any>(items.maps);

const types: Record<string, CasualMapCategory[]> = {};

for(const group of mapGroups) {
	if(!mapTypes.includes(group.mm_type)) continue;
	
	const category: CasualMapCategory = {
		name: str(group.localized_name),
		maps: []
	}

	for(const map of Object.values<any>(group.maplist)) {
		if(!map.enabled) continue;
		category.maps.push(mapInfo[map.name]);
	}

	category.maps.sort((a, b) => a.name.localeCompare(b.name));

	types[group.mm_type] ??= [];
	types[group.mm_type].push(category);
}

// Get the bit mask for our known maps
const masks: bigint[] = new Array(largestNumber + 1).fill(0n);
const categories = Object.values(types).flat();

for(const category of categories) {
	for(const map of category.maps) {
		const mask = 1n << map.bit;
		if((masks[map.number] & mask) > 0n) {
			console.error(`Map ${map.name} already has its bit set`);
		}
		
		masks[map.number] |= mask;
	}
}

// Write the output to $shared/maps.ts
let string = `import type { CasualMapCategory } from "$types/maps";\n\n` +
	"// This file is auto-generated by scripts/createMapList, do not edit by hand\n" +
	"export const mapBits = [\n";

for(let i = 0; i < masks.length; i++) {
	string += `    ${masks[i]}n,\n`;
}

string += "];\n\n" +
	"export const casualMaps: CasualMapCategory[] = [\n";

for(const category of categories) {
	string += `    {\n        name: "${category.name}",\n        maps: [\n`;

	for(const map of category.maps) {
		string += `            { name: "${map.name}", bit: ${map.bit}n, number: ${map.number} },\n`;
	}

	string += "        ]\n    },\n";
}

string += "];\n";

await writeFile("../shared/maps.ts", string);

function str(key: string): string {
	// Strip the # from the start of the key
	return strings[key.slice(1)];
}