import { casualMaps } from "$shared/maps";
import fs from "fs";

// This script determines all bits which can be set for casual maps
const numbers: bigint[] = new Array(8).fill(0n);

for(const category of casualMaps) {
	for(const map of category.maps) {
		const mask = 1n << map.bit;
		if((numbers[map.number] & mask) > 0n) {
			console.error(`Map ${map.name} already has its bit set`);
		}
		
		numbers[map.number] |= mask;
	}
}

let string = "// Generated by scripts/getMapBits- do not edit directly\n" +
	"export const mapBits = [\n";
for(const number of numbers) {
	string += `    ${number}n,\n`;
}
string += "];";

fs.writeFileSync("src/casual/mapBits.ts", string);
console.log("Done!");