import { TF2Class } from "$types/lobby";

// This leaves room for ambiguity between stock scout and stock engineer
export const startingHealths: Record<number, TF2Class[]> = {
    [70]: [TF2Class.Spy], // Kunai
    [100]: [TF2Class.Spy], // Big earner
    [110]: [TF2Class.Scout], // Sandman
    [125]: [TF2Class.Scout, TF2Class.Sniper, TF2Class.Engineer, TF2Class.Spy],
    [140]: [TF2Class.Medic], // vita-saw
    [150]: [TF2Class.Engineer, TF2Class.Demo, TF2Class.Medic], // gunslinger, eyelander
    [175]: [TF2Class.Pyro, TF2Class.Demo],
    [200]: [TF2Class.Demo, TF2Class.Soldier],
    [220]: [TF2Class.Soldier], // Batallion's backup
    [300]: [TF2Class.Heavy]
}

export const startingAmmo: Record<number, TF2Class[]> = {
    [3]: [TF2Class.Demo], // Persian persuader
    [12]: [TF2Class.Sniper], // Huntsman
    [16]: [TF2Class.Demo, TF2Class.Engineer], // Rescue Ranger
    // For some reason spy always is counted as having 20 ammo regardless of his actual clip
    [20]: [TF2Class.Soldier, TF2Class.Spy],
    [25]: [TF2Class.Sniper],
    [32]: [TF2Class.Scout, TF2Class.Engineer],
    [38]: [TF2Class.Medic], // Crusader's Crossbow
    [40]: [TF2Class.Pyro], // Dragon's Fury
    [60]: [TF2Class.Soldier], // Rocket jumper
    [150]: [TF2Class.Medic],
    [200]: [TF2Class.Pyro, TF2Class.Heavy]
}

export const maxClassHealths: Record<TF2Class, number> = {
    [TF2Class.Scout]: 185,
    [TF2Class.Soldier]: 330, // Battalion's Backup
    [TF2Class.Pyro]: 260,
    [TF2Class.Demo]: 350, // Boots + Max Heads,
    [TF2Class.Heavy]: 450,
    [TF2Class.Engineer]: 225, // Gunslinger,
    [TF2Class.Medic]: 225,
    [TF2Class.Sniper]: 185,
    [TF2Class.Spy]: 210 // Kunai
}

const allClassMelee = [TF2Class.Scout, TF2Class.Soldier, TF2Class.Pyro,
    TF2Class.Demo, TF2Class.Heavy, TF2Class.Medic, TF2Class.Sniper];
const allClasses = [...allClassMelee, TF2Class.Engineer, TF2Class.Spy];

export const killClasses: Record<string, TF2Class[]> = {
    "airstrike": [TF2Class.Soldier],
    "ai_flamethrower": [TF2Class.Pyro],
    "ambassador": [TF2Class.Spy],
    "amputator": [TF2Class.Medic],
    "annihilator": [TF2Class.Pyro],
    "apocofists": [TF2Class.Heavy],
    "armageddon": [TF2Class.Pyro],
    "atomizer": [TF2Class.Scout],
    "awper_hand": [TF2Class.Sniper],
    "axtinguisher": [TF2Class.Pyro],
    "backburner": [TF2Class.Pyro],
    "backstab": [TF2Class.Spy],
    "back_scatter": [TF2Class.Scout],
    "back_scratcher": [TF2Class.Pyro],
    "ball": [TF2Class.Scout],
    "bat": [TF2Class.Scout],
    "batsaber": [TF2Class.Scout],
    "battleaxe": [TF2Class.Demo],
    "battleneedle": [TF2Class.Medic],
    "bazaar_bargain": [TF2Class.Sniper],
    "big_earner": [TF2Class.Spy],
    "blackbox": [TF2Class.Soldier],
    "black_rose": [TF2Class.Spy],
    // Technically also from the grappling hook in mannpower but nobody plays mannpower
    "bleed_kill": [TF2Class.Scout, TF2Class.Engineer, TF2Class.Sniper],
    "blutsauger": [TF2Class.Medic],
    "bonesaw": [TF2Class.Medic],
    "boston_basher": [TF2Class.Scout],
    "bottle": [TF2Class.Demo],
    "brass_beast": [TF2Class.Heavy],
    "bread_bite": [TF2Class.Heavy],
    "bushwacka": [TF2Class.Sniper],
    "candy_cane": [TF2Class.Scout],
    "claidheamhmor": [TF2Class.Demo],
    "compound_bow": [TF2Class.Sniper],
    "cow_mangler": [TF2Class.Soldier],
    "crossing_guard": allClassMelee,
    "crusaders_crossbow": [TF2Class.Medic],
    "deflect_arrow": [TF2Class.Pyro],
    "deflect_flare": [TF2Class.Pyro],
    "deflect_promode": [TF2Class.Pyro],
    "deflect_rocket": [TF2Class.Pyro],
    "deflect_sticky": [TF2Class.Pyro],
    "degreaser": [TF2Class.Pyro],
    "demokatana": [TF2Class.Demo],
    "demoshield": [TF2Class.Demo],
    "detonator": [TF2Class.Pyro],
    "diamondback": [TF2Class.Spy],
    "disciplinary_action": [TF2Class.Soldier],
    "dragons_fury": [TF2Class.Pyro],
    "dragons_fury_bonus": [TF2Class.Pyro],
    "dumpster_device": [TF2Class.Soldier],
    "enforcer": [TF2Class.Spy],
    "eternal_reward": [TF2Class.Spy],
    "eureka_effect": [TF2Class.Engineer],
    "eviction_notice": [TF2Class.Heavy],
    "family_business": [TF2Class.Heavy],
    "fireaxe": [TF2Class.Pyro],
    "fists": [TF2Class.Heavy],
    "flamethrower": [TF2Class.Pyro],
    "flaregun": [TF2Class.Pyro],
    "force_a_nature": [TF2Class.Scout],
    "freedom_staff": allClassMelee,
    "frontier_justice": [TF2Class.Engineer],
    "fryingpan": allClassMelee,
    "gas_blast": [TF2Class.Pyro],
    "gloves": [TF2Class.Heavy],
    "gloves_running_urgently": [TF2Class.Heavy],
    "guillotine": [TF2Class.Scout],
    "ham_shank": allClassMelee,
    "headshot": [TF2Class.Sniper, TF2Class.Spy],
    "headtaker": [TF2Class.Demo],
    "holiday_punch": [TF2Class.Heavy],
    "holy_mackerel": [TF2Class.Scout],
    "hot_hand": [TF2Class.Pyro],
    "huntsman_flyingburn": [TF2Class.Sniper],
    "huntsman_headshot": [TF2Class.Sniper],
    "iron_bomber": [TF2Class.Demo],
    "iron_curtain": [TF2Class.Heavy],
    "knife": [TF2Class.Spy],
    "club": [TF2Class.Sniper],
    "kunai": [TF2Class.Spy],
    "lava_axe": [TF2Class.Pyro],
    "lava_bat": [TF2Class.Scout],
    "letranger": [TF2Class.Spy],
    "liberty_launcher": [TF2Class.Soldier],
    "loch_n_load": [TF2Class.Demo],
    "lollichop": [TF2Class.Pyro],
    "long_heatmaker": [TF2Class.Heavy],
    "loose_cannon": [TF2Class.Demo],
    "loose_cannon_impact": [TF2Class.Demo],
    "machina": [TF2Class.Sniper],
    "mailbox": [TF2Class.Pyro],
    "manmelter": [TF2Class.Pyro],
    "mantreads": [TF2Class.Soldier],
    "market_gardener": [TF2Class.Soldier],
    "maxgun": [TF2Class.Scout, TF2Class.Engineer],
    "memory_maker": allClassMelee,
    "minigun": [TF2Class.Heavy],
    "natascha": [TF2Class.Heavy],
    "nessieclub": [TF2Class.Demo],
    "nonnonviolent_protest": allClassMelee,
    "obj_minisentry": [TF2Class.Engineer],
    "obj_sentrygun1": [TF2Class.Engineer],
    "obj_sentrygun2": [TF2Class.Engineer],
    "obj_sentrygun3": [TF2Class.Engineer],
    "paintrain": [TF2Class.Soldier, TF2Class.Demo],
    "panic_attack": [TF2Class.Soldier, TF2Class.Pyro, TF2Class.Heavy, TF2Class.Engineer],
    "pep_brawlerblaster": [TF2Class.Scout],
    "pep_pistol": [TF2Class.Scout],
    "persian_persuader": [TF2Class.Demo],
    "phlogistinator": [TF2Class.Pyro],
    "pistol": [TF2Class.Scout, TF2Class.Engineer],
    "player_penetration": [TF2Class.Sniper],
    "player_penetration_headshot": [TF2Class.Sniper],
    "pomson": [TF2Class.Engineer],
    "powerjack": [TF2Class.Pyro],
    "prinny_machete": allClasses,
    "proto_syringe": [TF2Class.Medic],
    "pro_rifle": [TF2Class.Sniper],
    "pro_smg": [TF2Class.Sniper],
    "quake_rl": [TF2Class.Soldier],
    "quickiebomb_launcher": [TF2Class.Demo],
    "rainblower": [TF2Class.Pyro],
    "rescue_ranger": [TF2Class.Engineer],
    "reserve_shooter": [TF2Class.Soldier, TF2Class.Pyro],
    "revolver": [TF2Class.Spy],
    "righteous_bison": [TF2Class.Soldier],
    "robot_arm": [TF2Class.Engineer],
    "robot_arm_blender_kill": [TF2Class.Engineer],
    "robot_arm_combo_kill": [TF2Class.Engineer],
    "rocketlauncher_directhit": [TF2Class.Soldier],
    "samrevolver": [TF2Class.Spy],
    "sandman": [TF2Class.Scout],
    "saxxy": allClasses,
    "scattergun": [TF2Class.Scout],
    "scorch_shot": [TF2Class.Pyro],
    "scotland_shard": [TF2Class.Demo],
    "scout_sword": [TF2Class.Scout],
    "shahanshah": [TF2Class.Sniper],
    "sharp_dresser": [TF2Class.Spy],
    "shooting_star": [TF2Class.Sniper],
    "short_circuit": [TF2Class.Engineer],
    "short_stop": [TF2Class.Scout],
    "shotgun_primary": [TF2Class.Engineer],
    "shotgun_pyro": [TF2Class.Pyro],
    "shotgun_soldier": [TF2Class.Soldier],
    "shovel": [TF2Class.Soldier],
    "skullbat": allClassMelee,
    "sledgehammer": [TF2Class.Pyro],
    "smg": [TF2Class.Sniper],
    "sniperrifle": [TF2Class.Sniper],
    "soda_popper": [TF2Class.Scout],
    "solemn_vow": [TF2Class.Medic],
    "southern_hospitality": [TF2Class.Engineer],
    "splendid_screen": [TF2Class.Demo],
    "spy_cicle": [TF2Class.Spy],
    "steel_fists": [TF2Class.Heavy],
    "sticky_resistance": [TF2Class.Demo],
    "sword": [TF2Class.Demo],
    "sydney_sleeper": [TF2Class.Sniper],
    "syringegun_medic": [TF2Class.Medic],
    "taunt_demoman": [TF2Class.Demo],
    "taunt_guitar_kill": [TF2Class.Engineer],
    "taunt_heavy": [TF2Class.Heavy],
    "taunt_medic": [TF2Class.Medic],
    "taunt_pyro": [TF2Class.Pyro],
    "taunt_scout": [TF2Class.Scout],
    "taunt_sniper": [TF2Class.Sniper],
    "taunt_soldier": [TF2Class.Soldier],
    "taunt_spy": [TF2Class.Spy],
    "tf_projectile_arrow": [TF2Class.Sniper],
    "tf_projectile_mechanicalarmorb": [TF2Class.Engineer],
    "tf_projectile_pipe": [TF2Class.Demo],
    "tf_projectile_pipe_remote": [TF2Class.Demo],
    "tf_projectile_rocket": [TF2Class.Soldier],
    "the_capper": [TF2Class.Scout, TF2Class.Engineer],
    "the_classic": [TF2Class.Sniper],
    "the_maul": [TF2Class.Pyro],
    "the_winger": [TF2Class.Scout],
    "thirddegree": [TF2Class.Pyro],
    "tide_turner": [TF2Class.Demo],
    "tomislav": [TF2Class.Heavy],
    "tribal_kukri": [TF2Class.Sniper],
    "ubersaw": [TF2Class.Medic],
    "ullapool_caber": [TF2Class.Demo],
    "ullapool_caber_explosion": [TF2Class.Demo],
    "unarmed_combat": [TF2Class.Scout],
    "unique_pickaxe": [TF2Class.Soldier],
    "unique_pickaxe_escape": [TF2Class.Soldier],
    "voodoo_pin": [TF2Class.Spy],
    "warfan": [TF2Class.Scout],
    "warrior_spirit": [TF2Class.Heavy],
    "widowmaker": [TF2Class.Engineer],
    "wrangler_kill": [TF2Class.Engineer],
    "wrap_assassin": [TF2Class.Scout],
    "wrench": [TF2Class.Engineer],
    "wrench_golden": [TF2Class.Engineer],
    "wrench_jag": [TF2Class.Engineer]
}