const critRemaps: Record<string, string> = {
    tf_projectile_arrow: "huntsman_headshot",
    sniperrifle: "headshot",
    bazaar_bargain: "headshot",
    player_penetration: "player_penetration_headshot",
    pro_rifle: "headshot",
    the_classic: "headshot",
    shooting_star: "headshot",
    awper_hand: "headshot",
    ambassador: "headshot",
    machina: "headshot",
    knife: "backstab",
    eternal_reward: "backstab",
    kunai: "backstab",
    big_earner: "backstab",
    voodoo_pin: "backstab",
    sharp_dresser: "backstab",
    spy_cicle: "backstab",
    black_rose: "backstab"
};

export const knownIcons: Record<string, string> = {
    "airstrike": "Air Strike",
    "ai_flamethrower": "Nostromo Napalmer",
    "ambassador": "Ambassador",
    "amputator": "Amputator",
    "annihilator": "Neon Annihilator",
    "apocofists": "Apoco-Fists",
    "armageddon": "Armageddon",
    "atomizer": "Atomizer",
    "awper_hand": "Awper hand",
    "axtinguisher": "Axtinguisher",
    "backburner": "Backburner",
    "backstab": "Backstab",
    "back_scatter": "Back Scatter",
    "back_scratcher": "Back Scratcher",
    "ball": "Ball",
    "bat": "Bat",
    "batsaber": "Batsaver",
    "battleaxe": "Scotsman' Skullcutter",
    "battleneedle": "Vita-Saw",
    "bazaar_bargain": "Bazaar Bargain",
    "big_earner": "Big Earner",
    "blackbox": "Black Box",
    "black_rose": "Black Rose",
    "bleed_kill": "Bleed",
    "blutsauger": "Blutsauger",
    "bonesaw": "Bonesaw",
    "boston_basher": "Boston Basher",
    "bottle": "Bottle",
    "brass_beast": "Brass Beast",
    "bread_bite": "Bread Bite",
    "bushwacka": "Bushwacka",
    "candy_cane": "Candy Cane",
    "claidheamohmor": "Claidheamh Mor",
    "compound_bow": "Huntsman Afterburn",
    "cow_mangler": "Cow Mangler 5000",
    "crocodile": "Crocodile",
    "crossing_guard": "Crossing Guard",
    "crusaders_crossbow": "Crusader's Crossbow",
    "deflect_arrow": "Huntsman Reflect",
    "deflect_flare": "Flare Reflect",
    "deflect_promode": "Grenade Reflect",
    "deflect_rocket": "Rocket Reflect",
    "deflect_sticky": "Stickybomb Reflect",
    "degreaser": "Degreaser",
    "demokatana": "Half Zatoichi",
    "demoshield": "Chargin' Targe",
    "detonator": "Detonator",
    "diamondback": "Diamondback",
    "disciplinary_action": "Disciplinary Action",
    "dragons_fury": "Dragon's Fury",
    "dragons_fury_bonus": "Dragon's Fury",
    "dumpster_device": "Beggar's Bazooka",
    "enforcer": "Enforcer",
    "eternal_reward": "Your Eternal Reward",
    "eureka_effect": "Eureka Effect",
    "eviction_notice": "Eviction Notice",
    "family_business": "Family Business",
    "fireaxe": "Fire Axe",
    "fists": "Fists",
    "flamethrower": "Flamethrower",
    "flaregun": "Flare Gun",
    "force_a_nature": "Force-A-Nature",
    "freedom_staff": "Freedom Staff",
    "frontier_justice": "Frontier Justice",
    "fryingpan": "Frying Pan",
    "gas_blast": "Gas Blast",
    "gloves": "Killing Gloves of Boxing",
    "gloves_running_urgently": "Gloves of Running Urgently",
    "golden_fryingpan": "Golden Frying Pan",
    "guillotine": "Flying Guillotine",
    "hale_charge": "Sweeping Charge",
    "hale_megapunch": "Saxton Punch!",
    "hale_megapunch_collateral": "Saxton Punch AOE",
    "hale_punch": "Hale Punch",
    "hale_slam_collateral": "Mighty Slam",
    "hale_taunt": "Hale Tauntkill",
    "ham_shank": "Ham Shank",
    "headshot": "Headshot",
    "headtaker": "HHH's Headtaker",
    "holiday_punch": "Holiday Punch",
    "holymackerel": "Holy Mackerel",
    "hot_hand": "Hot Hand",
    "huntsman_flyingburn": "Huntsman Burning Arrow",
    "huntsman_headshot": "Huntsman Headshot",
    "iron_bomber": "Iron Bomber",
    "iron_curtain": "Iron Curtain",
    "knife": "Knife",
    "club": "Kukri",
    "kunai": "Kunai",
    "lava_axe": "Sharpened Volcano Fragment",
    "lava_bat": "Sun-on-a-Stick",
    "letranger": "L'Etranger",
    "liberty_launcher": "Liberty Launcher",
    "loch_n_load": "Loch-n-Load",
    "lollichop": "Lollichop",
    "long_heatmaker": "Huo-Long Heater",
    "loose_cannon": "Loose Cannon",
    "loose_cannon_impact": "Loose Cannon",
    "machina": "Machina",
    "mailbox": "Postal Pummeler",
    "manmelter": "Manmelter",
    "mantreads": "Mantreads",
    "market_gardener": "Market Gardener",
    "maxgun": "Lugermorph",
    "memory_maker": "Memory Maker",
    "minigun": "Minigun",
    "natascha": "Natascha",
    "nessieclub": "Nessie's Nine Iron",
    "nonnonviolent_protest": "Conscientious Objector",
    "obj_minisentry": "Mini-Sentry",
    "obj_sentrygun1": "Level 1 Sentry",
    "obj_sentrygun2": "Level 2 Sentry",
    "obj_sentrygun3": "Level 3 Sentry",
    "paintrain": "Pain Train",
    "panic_attack": "Panic Attack",
    "pep_brawlerblaster": "Baby Face's Blaster",
    "pep_pistol": "Pretty Boy's Pocket Pistol",
    "persian_persuader": "Persian Persuader",
    "phlogistinator": "Phlogistinator",
    "pistol": "Pistol",
    "pistol_scout": "Pistol",
    "player": "Player",
    "player_penetration": "Penetration",
    "player_penetration_headshot": "Penetration Headshot",
    "pomson": "Pomson 6000",
    "powerjack": "Powerjack",
    "prinny_machete": "Prinny Machete",
    "proto_syringe": "Overdose",
    "pro_rifle": "Hitman's Heatmaker",
    "pro_smg": "Cleaner's Carbine",
    "quake_rl": "The Original",
    "quickiebomb_launcher": "Quickiebomb Launcher",
    "rainblower": "Rainblower",
    "rescue_ranger": "Rescue Ranger",
    "reserve_shooter": "Reserve Shooter",
    "revolver": "Revolver",
    "righteous_bison": "Righteous Bison",
    "robot_arm": "Gunslinger",
    "robot_arm_blender_kill": "Arm Blender",
    "robot_arm_combo_kill": "Gunslinger Combo",
    "rocketlauncher_directhit": "Direct Hit",
    "samrevolver": "Big Kill",
    "sandman": "Sandman",
    "saxxy": "Saxxy",
    "scattergun": "Scattergun",
    "scorch_shot": "Scorch Shot",
    "scotland_shard": "Scottish Handshake",
    "scout_sword": "Three-Rune Blade",
    "shahanshah": "Shahanshah",
    "shark": "Shark",
    "sharp_dresser": "Sharp Dresser",
    "shooting_star": "Shooting Star",
    "short_circuit": "Short Circuit",
    "shortstop": "Shortstop",
    "shotgun_primary": "Shotgun",
    "shotgun_pyro": "Shotgun",
    "shotgun_soldier": "Shotgun",
    "shotgun_hwg": "Shotgun",
    "shovel": "Shovel",
    "skullbat": "Bat Outta Hell",
    "sledgehammer": "Homewrecker",
    "smg": "SMG",
    "sniperrifle": "Sniper Rifle",
    "soda_popper": "Soda Popper",
    "solemn_vow": "Solemn Vow",
    "southern_hospitality": "Southern Hospitality",
    "spellbook_skeleton": "Skeleton Horde Spell",
    "spellbook_boss": "Monoculus Spell",
    "spellbook_teleport": "Shadow Leap Spell",
    "spellbook_lightning": "Ball O' Lightning Spell",
    "spellbook_blastjump": "Blast Jump Spell",
    "spellbook_meteor": "Meteor Shower Spell",
    "spellbook_fireball": "Fireball Spell",
    "spellbook_athletic": "Minify Spell",
    "spellbook_bats": "Bats Spell",
    "spellbook_mirv": "Pumpkin MIRV Spell",
    "splendid_screen": "Splendid Screen",
    "spy_cicle": "Spy-Cicle",
    "steel_fists": "Fists of Steel",
    "sticky_resistance": "Scottish Resistance",
    "suicide": "Suicide",
    "sword": "Eyelander",
    "sydney_sleeper": "Sydney Sleeper",
    "syringegun_medic": "Syringe Gun",
    "taunt_demoman": "Barbarian Swing",
    "taunt_guitar_kill": "Guitar Smash",
    "taunt_heavy": "High Noon",
    "taunt_medic": "Uberslice",
    "taunt_pyro": "Hadouken",
    "taunt_scout": "Grand Slam",
    "taunt_sniper": "Arrow Stab",
    "taunt_soldier": "Kamikaze",
    "taunt_spy": "Fencing",
    "telefrag": "Telefrag",
    "tf_projectile_arrow": "Huntsman",
    "tf_projectile_mechanicalarmorb": "Short Circuit Orb",
    "tf_projectile_pipe": "Grenade Launcher",
    "tf_projectile_pipe_remote": "Stickybomb Launcher",
    "tf_projectile_rocket": "Rocket Launcher",
    "tf_pumpkin_bomb": "Pumpkin Bomb",
    "the_capper": "C.A.P.P.E.R",
    "the_classic": "The Classic",
    "the_maul": "Maul",
    "the_winger": "Winger",
    "thirddegree": "Third Degree",
    "tide_turner": "Tide Turner",
    "tomislav": "Tomislav",
    "tribal_kukri": "Tribalman's Shiv",
    "ubersaw": "Ubersaw",
    "ullapool_caber": "Ullapool Caber",
    "ullapool_caber_explosion": "Ullapool Caber Explosion",
    "unarmed_combat": "Unarmed Combat",
    "unique_pickaxe": "Equalizer",
    "unique_pickaxe_escape": "Escape Plan",
    "voodoo_pin": "Wanga Prick",
    "warfan": "Fan O'War",
    "warrior_spirit": "Warrior's Spirit",
    "widowmaker": "Widowmaker",
    "world": "World",
    "wrangler_kill": "Wrangler",
    "wrap_assassin": "Wrap Assassin",
    "wrench": "Wrench",
    "wrench_golden": "Golden Wrench",
    "wrench_jag": "Jag"
}
const backupIcon = "suicide";

export function getWeaponImage(weapon: string, crit: boolean) {
    if (crit && critRemaps[weapon]) weapon = critRemaps[weapon];

    if (!(weapon in knownIcons)) {
        return `/killfeed/Killicon_${backupIcon}.png`;
    }
    return `/killfeed/Killicon_${weapon}.png`;
}

export const mergeWith: Record<string, string[]> = {
    "machina": ["player_penetration"],
    "ullapool_caber": ["ullapool_caber_explosion"],
    "dragons_fury": ["dragons_fury_bonus"],
    "short_circuit": ["tf_projectile_mechanicalarmorb"],
    "loose_cannon": ["loose_cannon_impact"],
    "robot_arm": ["robot_arm_combo_kill", "robot_arm_blender_kill"],
    // For  some reason compound_bow is for arrow afterburn kills
    "tf_projectile_arrow": ["taunt_sniper", "huntsman_flyingburn", "compound_bow"],
    "ubersaw": ["taunt_medic"],
    "frontier_justice": ["taunt_guitar_kill"]
}

export const mergedWeapons: Record<string, string> = {};
for(let weapon in mergeWith) {
    for(let merge of mergeWith[weapon]) {
        mergedWeapons[merge] = weapon;
    }
}