# Taken from https://jon.sprig.gs/blog/post/2442
name: Create Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: false
          body_path: .github/release-notes.md

  build_release:
    name: Build Release
    needs: create_release
    permissions:
      contents: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: linux
          - os: windows-latest
            release_suffix: windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install GTK development packages
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y make pkg-config libgtk-3-dev

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Run Linux Build
        if: matrix.os == 'ubuntu-latest'
        run: cd backend && bun run compile --zip tfview_${{ github.ref_name }}_linux

      - name: Download ResourceHacker
        if: matrix.os == 'windows-latest'
        run: |
          curl https://www.angusj.com/resourcehacker/resource_hacker.zip -o C:\resource_hacker.zip
          powershell -command "Expand-Archive -Force C:\resource_hacker.zip C:\resource_hacker"

      - name: Run Windows Build
        if: matrix.os == 'windows-latest'
        run: cd backend && bun run compile --zip tfview_${{ github.ref_name }}_windows --resourcehacker "C:\resource_hacker\ResourceHacker.exe"

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: backend/dist/tfview_${{ github.ref_name }}_${{ matrix.release_suffix }}.zip